### ISSUE TITLE
CMFA ESR set of sensors

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Administration#30]
https://github.com/biometricITC/Administration/pull/28/files#diff-0322fe0bbf26aa2800fc98c52cb2bf5bd216701bdf2d855e8467f9247b3be429R132

Should the ESR state the minimum number of sensors (I would assume 2), or provide some other expectation? I know the ESRs are fairly broad statements, but I wonder if "an adequate set of" should be "at least two". I get the point that this should be some sort of combination with at least some sensors that are "trusted" highly, but I wonder it this should be explicitly stated in the ESR.

The one issue with stating it like that is that it means that somehow we have to define (or at least provide examples) of what we mean in the document.

**Comment by n-kai** [comment]
Definition of "an adequate set of" sensors is those sensors that an attacker who possess the basic attack potential can't spoof at once (as of the date of evaluation) and its meaning is clear for me. If "an adequate set of" is replaced with "at least two", does it means that vendor is allowed configure those two sensors that both can be easily spoofed?

**Comment by gfiumara** [comment]
I think you have to define the minimum accuracy + minimum PAD rate before answering this (see also #23 and #22). If the single sensor you're using is highly accurate + not susceptible to spoof (e.g., some _future_ continuous fingerprint scanner), a single sensor would be enough. On the contrary, >1 highly-spoofable sensors (microphone, GPS, bluetooth, ...) doesn't change what you warn against in the ESR note IMO.

The second part of the note, "input from non-secure execution environment," might discount some (all?) of the highly-spoofable sensors? Is that statement sufficient?

**Comment by woodbe** [comment]
@n-kai so I think that definition is good, but then we need to specify what that means somewhere with some examples or explanations so what we are expecting as "adequate" cannot be interpreted in some manner we don't expect. My only reason for specifying "at least 2" was to put a simple minimum boundary on it, but if we add something to explain it, then I will be OK with the definition.

**Comment by gregott** [comment]
“Those sensors that an attacker who possess the basic attack potential can't spoof at once (as of the date of evaluation)” causes the problem of how to calculate the combined attack potential of the multiple sensor spoof attempt.  Should the attacker’s elapsed time for each sensor be added or can the time to develop the attacks be run concurrently?  I assume the Expertise will take the value of the highest of the attacks??  Same for Knowledge of the TOE and Window of Opportunities??  I agree that this definition makes sense.  I am not sure how the labs will test against it.  I also think we can have both a minimum set of 2 (otherwise it would not be multi-factor) and something like this definition to avoid having factors combined in a trivial way.

**Comment by n-kai** [comment]
My rough idea is as follows but don't have time to verify it so it may include some mistakes and I don't know the state of art of the CMFA so it can't be applied to the latest technology. So pls correct  me if I am wrong. 

1) MDF PP and its extended packages include security requirements for Bluetooth, IEEE 802.11 and Wifi connection etc. So if the devices is validated to conform to those PP and pkgs, it can be assumed that such network connection is established securely by those evaluated sensors.

2) "an adequate set of" sensors" is a set of sensors that includes at least one evaluated sensor (i.e. Bluetooth, IEEE 802.11 or Wifi). Vendors can add other sensors such as GPS to improve the usability of CMFA but CMFA score should be determined mainly by input from such evaluated sensors.

3) Of course vendors can allow user to configure sensors without such evaluated sensors for CMFA (e.g. when they go abroad), such configuration should be out of scope of CMFA PP evaluation.
