### ISSUE TITLE
Learning CMFA?

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Administration#32]
I know that we have talked about how CMFA would learn who you are (more than just checking with the sensors, but in the combination), but I am not sure that the state of the art is there yet today. This isn't explicitly stated in any ESR, but it does come out in the privacy concerns that are raised since it basically treats the entire CMFA as a biometric system. 

Do we need an ESR (which I would make optional) about this as a requirement? Ideally this is where the tech goes, but I don't know that it is there yet (for production, anyway). Today I think everything is much more about fixed points: are you on this network, in that location, connection to some device (paired together with something like face or a sensor on a watch or something). If something like gait is being used, it is likely just being reported from the biometric sensor, the CMFA doesn't know any details, and it isn't combining them to learn that you walk somewhere at specific times.

**Comment by n-kai** [comment]
@woodbe 
_I am not sure that the state of the art is there yet today_
I also don't know the state of art but if the learning capability of CMFA is rarely implemented in the mobile devices, such functional requirement should be defined as optional one in the ESR.

_fixed points: are you on this network, in that location, connection to some device_
Personal data is defined under the GDPR as "any information which is related to an identified or identifiable natural person" so if the CMFA traces and records such data, it should be protected as personal data (i.e. this security requirement should be defined as the current ESR does)

**Comment by gregott** [comment]
I agree.  Make it optional but if it is used, place requirements on protection of PII.

**Comment by woodbe** [comment]
The text for the learning CMFA is:

> CMFA shall learn user behavior that is considered normal and utilize this dynamic configuration data in addition to static configurations to determine the confidence rating

This needs further discussion for agreement. I am removing the note in the pull request (and leave it as it is for now) so that pull request can either be updated based on further comment or merged and further updates made separately.

**Comment by woodbe** [comment]
Since we would have to write requirements for this optional part, and this is a future thing, I think this can be added in the future with a PPM revision (and it would fall under the "type of sensor" being used).

I do not think this needs to be explicitly called out in the ESR today.
